AdminBundle\Entity\epizy_logiciels:
    type: entity
    table: null
    repositoryClass: AdminBundle\Repository\epizy_logicielsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libele:
            type: string
            length: 255
        etat:
            type: integer
            nullable: true
        created:
            type: datetime
    lifecycleCallbacks: {  }
    oneToMany:
        demandeur_cvs:
            targetEntity: epizy_demandeur_cvs
            mappedBy: logiciel_id
            cascade: [persist]
